doctrine:
    orm:
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            oneLocale:
                class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                enabled: true

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            sluggable: true
            sortable: true
            softdeleteable: true
            translatable: true

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Purethink\CoreBundle\Entity\User
    group:
        group_class:   Purethink\CoreBundle\Entity\Group
    from_email:
        address: "%mailer_user%"
        sender_name: PureThink

a2lix_i18n_doctrine:
    manager_registry: doctrine

a2lix_translation_form:
    locales: [pl, en]

doctrine_migrations:
    table_name: migration_versions

sonata_classification:
    class:
        tag:          Purethink\CoreBundle\Entity\Tag
        category:     Purethink\CoreBundle\Entity\Category
        collection:   Purethink\CoreBundle\Entity\Collection
        context:      Purethink\CoreBundle\Entity\Context
        media:        Purethink\CoreBundle\Entity\Media
    admin:
        tag:
            class:        Sonata\ClassificationBundle\Admin\TagAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        category:
            class:        Sonata\ClassificationBundle\Admin\CategoryAdmin
            controller:   SonataClassificationBundle:CategoryAdmin
            translation:  SonataClassificationBundle
        collection:
            class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        context:
            class:        Sonata\ClassificationBundle\Admin\ContextAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle

sonata_media:
    class:
        media: Purethink\CoreBundle\Entity\Media
        gallery: Purethink\CoreBundle\Entity\Gallery
        gallery_has_media: Purethink\CoreBundle\Entity\GalleryHasMedia
        category: Purethink\CoreBundle\Entity\Category
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100, quality: 70 }
                big:   { width: 500, quality: 70 }
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

sonata_user:
    class:
        user: Purethink\CoreBundle\Entity\User
        group: Purethink\CoreBundle\Entity\Group
    impersonating:
        route: page
        parameters: { path: / }
    manager_type: orm
    profile:
        dashboard:
            blocks:
                - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Welcome!</h2> This is a sample user profile dashboard, feel free to override it in the configuration! Want to make this text dynamic? For instance display the user's name? Create a dedicated block and edit the configuration!"} }
        menu:
            - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
            - { route: 'sonata_user_change_password', label: 'change_password', domain: 'SonataUserBundle'}
        form:
            type: sonata_user_profile
            handler: sonata.user.profile.form.handler.default
            name: sonata_user_profile_form
            validation_groups:
                - Profile
                - Default